vcenter_hostname:
vcenter_username:
vcenter_password:
vcenter_folder:
vcenter_datacenter:
vcenter_cluster:
vcenter_datastore:
dns_servers: ["1.1.1.1", "1.0.0.1"]
vm_gateway: 192.168.0.1
vm_template: rocky-template
vm_first_ip: 192.168.0.101
vm_netmask: 255.255.255.0
servers:
  - df1
  - df2
  - df3
