---
all:
  vars:
    domain: kaya.lab
    # proxy: http://192.168.0.4:3128
    ansible_user: root
    mapr_user: mapr
    mapr_group: mapr
    mapr_uid: 5000
    mapr_gid: 5000
    mapr_pass: mapr123
    mapr_repo: http://package.mapr.hpe.com/releases/v7.3.0
    eep_repo: http://package.mapr.hpe.com/releases/MEP/MEP-9.1.1
    mapr_gpgkey: http://package.mapr.hpe.com/releases/pub/maprgpg.key
    install_eep: true
    mapr_disks: /dev/sdb
    cluster_name_core: core.kaya.lab
    cluster_name_edge: edge.kaya.lab
    secure_files:
      - maprhsm.conf
      - maprkeycreds.conf
      - maprkeycreds.jceks
      - maprserverticket
      - maprtrustcreds.conf
      - maprtrustcreds.jceks
      - ssl_keystore
      - ssl_keystore.p12
      - ssl_keystore.pem
      - ssl_keystore-signed.pem
      - ssl_truststore
      - ssl_truststore.p12
      - ssl_truststore.pem
      - ssl_userkeystore
      - ssl_userkeystore.p12
      - ssl_userkeystore.pem
      - ssl_userkeystore-signed.pem
      - ssl_usertruststore
      - ssl_usertruststore.p12
      - ssl_usertruststore.pem
      - tokens/
    ssh_private_key_file: ~/.ssh/id_rsa

core:
  hosts:
    192.168.205.87:

edge:
  hosts:
    # 192.168.0.34:
